os: linux

dist: focal

language: c

services:
    - docker

install:
    - ./mk_dockerfile.sh
    - docker-compose build

script:
    - docker-compose run $(bash <(curl -s https://codecov.io/env)) tests

notifications:
    email:
        on_success: change
        on_failure: always

env:
    - PG_VERSION=14 LEVEL=nightmare
    - PG_VERSION=14 LEVEL=hardcore
    - PG_VERSION=14
    - PG_VERSION=13 LEVEL=nightmare
    - PG_VERSION=13 LEVEL=hardcore
    - PG_VERSION=13
    - PG_VERSION=12 LEVEL=nightmare
    - PG_VERSION=12 LEVEL=hardcore
    - PG_VERSION=12
    - PG_VERSION=11 LEVEL=nightmare
    - PG_VERSION=11 LEVEL=hardcore
    - PG_VERSION=11
    - PG_VERSION=10

# XXX: consider fixing nightmare mode
matrix:
    allow_failures:
        - env: PG_VERSION=11 LEVEL=nightmare
        - env: PG_VERSION=12 LEVEL=nightmare
        - env: PG_VERSION=13 LEVEL=nightmare
        - env: PG_VERSION=14 LEVEL=nightmare
